name: Ubuntu-20.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: |
        sudo apt install build-essential libgmp-dev z3 opam gcc-aarch64-linux-gnu

    - name: Build
      run: |
        cargo test
